[package]
name = "qrcoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rqrr = "0.5.1"
image = "0.24.3"
cli-clipboard = "0.2.1"
screenshots = "0.4.4"
qrcode-png = "0.4.1"
clap = "3.2.22"
